[2023-08-15 20:11:28,790] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-08-15 20:11:28,796] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-08-15 20:11:28,796] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:11:28,796] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:11:28,796] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:11:28,821] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-05-29 00:00:00+00:00
[2023-08-15 20:11:28,824] {standard_task_runner.py:52} INFO - Started process 48035 to run task
[2023-08-15 20:11:28,830] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-05-29T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmp1ybkc65o', '--error-file', '/tmp/tmprtjvqhzp']
[2023-08-15 20:11:28,830] {standard_task_runner.py:80} INFO - Job 125: Subtask extrai_dados
[2023-08-15 20:11:28,890] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:11:28,910] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 48035. PIDs of all processes in the group: [48035]
[2023-08-15 20:11:28,910] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 48035
[2023-08-15 20:11:28,917] {process_utils.py:75} INFO - Process psutil.Process(pid=48035, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='20:11:28') (48035) terminated with exit code Negsignal.SIGTERM
[2023-08-15 20:11:33,501] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-08-15 20:11:33,501] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-08-15 20:11:33,506] {local_task_job.py:101} INFO - Task is not able to be run
[2023-08-15 20:30:39,243] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-08-15 20:30:39,249] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-08-15 20:30:39,249] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:30:39,249] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:30:39,250] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:30:39,556] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-05-29 00:00:00+00:00
[2023-08-15 20:30:39,559] {standard_task_runner.py:52} INFO - Started process 52767 to run task
[2023-08-15 20:30:39,564] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-05-29T00:00:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpqjiywao7', '--error-file', '/tmp/tmpmmfh_l67']
[2023-08-15 20:30:39,565] {standard_task_runner.py:80} INFO - Job 201: Subtask extrai_dados
[2023-08-15 20:30:39,898] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:30:40,663] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-05-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-29T00:00:00+00:00
[2023-08-15 20:30:40,779] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:30:40,785] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230529T000000, start_date=20230815T203039, end_date=20230815T203040
[2023-08-15 20:30:41,384] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:30:41,401] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-15 20:44:55,363] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-08-15 20:44:55,369] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-08-15 20:44:55,369] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:55,370] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:44:55,370] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:44:55,392] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2023-05-29 00:00:00+00:00
[2023-08-15 20:44:55,395] {standard_task_runner.py:52} INFO - Started process 57715 to run task
[2023-08-15 20:44:55,400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2023-05-29T00:00:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmpcu7yb3zw', '--error-file', '/tmp/tmpbj8nd6qd']
[2023-08-15 20:44:55,401] {standard_task_runner.py:80} INFO - Job 301: Subtask extrai_dados
[2023-08-15 20:44:55,461] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2023-05-29T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:44:55,540] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-05-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-29T00:00:00+00:00
[2023-08-15 20:44:55,618] {python.py:173} INFO - Done. Returned value was: None
[2023-08-15 20:44:55,625] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20230529T000000, start_date=20230815T204455, end_date=20230815T204455
[2023-08-15 20:44:55,652] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-15 20:44:55,670] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
